version: "3.7"
services:
  nodejs:
    container_name: nodejs
    build:
      context: .
    restart: always
    expose: 
      - "3000"    # expose the container only internally
    networks:
      - backnet

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:8080"
    links:
      - "nodejs:nodejs"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backnet

networks:
  backnet: